+TITLE: Hobbies

* Canes callidi ossa colligunt.
The clever dogs collect the bones.


* Pupae in sella sedent.
The dolls sit in the chair.

* Plurimas gemmas colligitis.
You collect very many gems.

* Gemmas aestimare soleo.
I usually appraise the gems.

* In atrio sellas colligimus.
We collect chairs in the atrium.

* Psittaci cum pupa loquuntur.
The parrots speak with the doll.

* Canis plurima ossa colligit.
The dog collects very many bones.

* "Pupa saltat!" Marcus exclamat.
"The doll dances!" Marcus exclaims.

* Senes ebrii in templo saltant.
The drunk old men dance in the temple.

* Ego noctu saltare soleo.
I usually dance at night.

* Bibliotheca volumina habet.
The library has books.

* Pictor pingere vult.
The painter wants to paint.

* Ubi in urbe saltatis?
Where do you dance in the city?

* Hic canis in pavimento dormire solet.
This dog usually sleep on the floor.

* Iuvenis saltare solet.
The young man usually dances.

* Pupas et ossa colligo.
I collect dolls and bones.

* Quis pupas colligere vult?
Who wans to collect dolls?

* Plurimas pupas colligere solet.
He usually collect very many dolls.

* Fures gemmas et picturas colligunt.
The thieves collect the gems and the pictures.

* Marcus in foro ambulare solet.
Marcus ususally walk in the forum.

* Ego litteras tibi mittere volo.
I want to send you letters.

* Tu cum psittaco cantas.
You sing with the parrot.

* Cantatis et saltatis.
You sing and dance.

* Pueri et puellae Germanice cantant.
The boys and girls sing in German.

* Marcus bene cantat.
Marcus sings well.

* Saepe cantamus.
We often sing.

* Marcus ebrius suaviter cantare vult.
The drunk Marcus wants to sing sweetly.

* Saepe suaviter cantamus.
Often we sing sweetly.

* Togam candiam vendere vult.
He want to sell the white toga.

* Interdiu ambulare non volo.
During the day I do not want to walk.

* Ille psittacus suaviter cantare potest.
That parrot can sing sweetly.

* Placetne tibi celeriter ambulare?
Do you like to walk quickly?

* Mustelae callidae celeriter currunt.
The clever weasels run quickly.

* In bibliotheca legere vultis.
YOu want to read in the library.

* Quo curritis?
To where do you run?

* Quo curris?
To where do you run?

* Corinna mane currit.
Corinna runs early.

* Saepe ambulamus et currimus.
Often we walk and run.

* Mores plurimos habet.
He has very many habits.

* Mos Novi Eboraci est suaviter cantare.
It is the custom in New York to sing sweetly.

* Currere tibi placet.
You like to run.

* Mores antiqui sunt plurimi.
There are very many ancient customs.

* Domum curro.
I run home.

* Mihi fabulam narras.
You tell me a story.

* Minerva et Mars fabulam narrant.
Minerva and Mars tell a story.

* Marcus plurimas fabulas narrat.
Marcus tells very many stories.

* Tu fabulam antiquam narrare vis.
You want to tell an ancient story.

* Fabulam narrare vis.
You want to tell a story.

* In platea currimus.
We run in the street.

* Noctu Marcus natare solet.
Marcus usually swims at night.

* In urbe non natas.
You don't swim in the city.

* Plurimae piscinae in urbe non sunt.
There are not very many ponds in the city.

* Mustela callida ad forum ire solet.
The clever weasel usually goes to the forum.

* Ego ad piscinam curro.
I run to the pond.

* Quomodo nato?
How do I swim?

* Plateae in urbe sunt.
The streets are in the city.

* Marcus in piscina natat.
Marcus swims in the pond.

* In piscina lente natant.
They swim slowly in the pond.

* Piscina est in platea.
The pond is in the courtyard.

* Natare aut saltare solet.
He usually swims or dances.
