#+TITLE: Skill

* Senex otiosus librum legit.
The old man reads a book

* Suntne psittaci otiosi?
Are the parrots leisurely?

* Psittacos iratos non pulsatis.
You do not hit angry parrots.

* Livia est fessa et irata.
Livia is tired and angry.

* Filias negotiosas habeo.
I have busy daughters.

* Tu psittacum non pulsas.
You do not hit the parrot.

* Feminae otiosae litteras multas scribunt.
The lessirely women wirte mnay letters.

* Iuvenis irati pugnant.
The angle young men fight.

* Livia tres filios negotiosos habet.
Livia has tree busy sons

* Iuvenis cum psittaco irato in foro est.
The young is in the forum with an angry parrot.

* Coquus ignavus non dormit.
The lazy cook does not cock.

* Psittacus eius est ebius.

* Milites coquum ignavum pulsant.
The soldiers hit the lazy rock.

* Tres filias placidas habeo.
I have three calm daughters.

* Contubernalis pugnat.
The comrade fights.

* Pueri senes perfidos numerant.
The boys count the deceitful old men.

* Senex comitem habet.
The old man has a comrade.

* Pueros placidos docemus.
We teach calm boys.

* Comes perfidus non pugnat.
The deceitful comrade does not fight.

* Psittacum ebrium et perfidum habeo.
I have a drunk and deceitful parrot.

* Puellas perfidas non docemus.
We do not teach deceitful girls.

* Puella perfida psittacum pulsat.
The deceitful girl hit the parrot.

* Puellae in ludo sunt tacitae.
The girls in school are quiet.

* Periti pugnamus.
We skilled people fight.

* Senex tacitus et femina tacita dormiunt.
The quite old man and the quite woman are sleeping.

* Comites sententias nostras sciunt.
The comrades know our opinions.

* Magister pueros impios non pulsat.
The teacher does not hit the undutiful boys.

* Fortasse comites sunt perfidi et impii.
Perhaps the comrades are deceitful and undutiful.

* Ego nostram sententiam scio.
I know our opinion.

* Iuvenis impius librum non legit.
The disrespectful young man does not read the book.

* Interdum sententiae sunt impiae.
Sometimes the opinions are wicked.

* Fortasse libros scitis.
Perhaps you know the books.

* Interdum placidus sum.
Sometimes I am calm.
